### ISSUE TITLE
instance system.adapter.onvif.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

### ISSUE THREAD

**Issue by Roellen** [iobroker-community-adapters/ioBroker.onvif#130]
**Describe the bug**  

Somehow it seems that the onvif adapter stops my js-controller. But I can't figure out why?

`<html>
<body>

host.iobroker-lxc | 2024-02-18 13:16:32.819 | error | instance system.adapter.onvif.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker-lxc | 2024-02-18 13:16:32.819 | error | Caught by controller[0]: at processTicksAndRejections (node:internal/process/task_queues:82:21)
host.iobroker-lxc | 2024-02-18 13:16:32.819 | error | Caught by controller[0]: at endReadableNT (node:internal/streams/readable:1400:12)
host.iobroker-lxc | 2024-02-18 13:16:32.819 | error | Caught by controller[0]: at IncomingMessage.emit (node:domain:489:12)
host.iobroker-lxc | 2024-02-18 13:16:32.819 | error | Caught by controller[0]: at IncomingMessage.emit (node:events:529:35)
host.iobroker-lxc | 2024-02-18 13:16:32.819 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/onvif/lib/cam.js:297:4)
host.iobroker-lxc | 2024-02-18 13:16:32.819 | error | Caught by controller[0]: at parseSOAPString (/opt/iobroker/node_modules/onvif/lib/utils.js:108:3)
host.iobroker-lxc | 2024-02-18 13:16:32.819 | error | Caught by controller[0]: at Cam.<anonymous> (/opt/iobroker/node_modules/onvif/lib/events.js:309:14)
host.iobroker-lxc | 2024-02-18 13:16:32.819 | error | Caught by controller[0]: TypeError: callback.call is not a function
onvif.0 | 2024-02-18 13:16:32.716 | error | callback.call is not a function
onvif.0 | 2024-02-18 13:16:32.716 | error | TypeError: callback.call is not a function at Cam.<anonymous> (/opt/iobroker/node_modules/onvif/lib/events.js:309:14) at parseSOAPString (/opt/iobroker/node_modules/onvif/lib/utils.js:108:3) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/onvif/lib/cam.js:297:4) at IncomingMessage.emit (node:events:529:35) at IncomingMessage.emit (node:domain:489:12) at endReadableNT (node:internal/streams/readable:1400:12) at processTicksAndRejections (node:internal/process/task_queues:82:21)
onvif.0 | 2024-02-18 13:16:32.715 | error | uncaught exception: callback.call is not a function

**Comment by mcm1957** [comment]
This log shows "only" a crash of the adapter. The js-controller should conatinue to work normally

**Comment by TA2k** [comment]
please use v1.1.2
