### ISSUE TITLE
Fail to add my camera Tp-Link VIGI C540

### ISSUE THREAD

**Issue by Osrx** [iobroker-community-adapters/ioBroker.onvif#49]
Hello!
I fail to add my camera Tp-Link VIGI C540.

But it can be added via url: http://10.100.3.6:2020/onvif/device_service in "ONVIF Device Manager" on my PC.

Debug is down here.
As far as I understand it returns some data, but error message write: "Failed to login to 10.100.3.6:2020"
This camera supports ONVIF protocol as it is stated on developer page:
https://static.tp-link.com/upload/product-overview/2022/202211/20221118/VIGI%20C540(UN)1.0_datasheet.pdf

Thank you for this project! My another camera works well.

`
<html><body>

onvif.1 | 2023-09-05 14:31:22.913 | info | Found devices:
-- | -- | -- | --
onvif.1 | 2023-09-05 14:31:22.913 | info | Manual search finished
onvif.1 | 2023-09-05 14:31:22.912 | info | Data: undefined xml: undefined
onvif.1 | 2023-09-05 14:31:22.912 | debug | Error: ONVIF SOAP Fault: error     at /opt/iobroker/node_modules/iobroker.onvif/lib/onvif/lib/utils.js:113:19     at Parser.<anonymous> (/opt/iobroker/node_modules/xml2js/lib/parser.js:304:18)     at Parser.emit (events.js:400:28)     at Parser.emit (domain.js:475:12)     at SAXParser.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:262:26)     at emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35)     at emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)     at closeTag (/opt/iobroker/node_modules/sax/lib/sax.js:889:7)     at SAXParser.write (/opt/iobroker/node_modules/sax/lib/sax.js:1436:13)     at Parser.exports.Parser.Parser.parseString (/opt/iobroker/node_modules/xml2js/lib/parser.js:323:31)
onvif.1 | 2023-09-05 14:31:22.910 | info | Error Error: ONVIF SOAP Fault: error
onvif.1 | 2023-09-05 14:31:22.909 | error | Failed to login to 10.100.3.6:2020 with admin:y***************-
onvif.1 | 2023-09-05 14:31:22.906 | debug | Raw response: <?xml version="1.0" encoding="UTF-8"?> <SOAP-ENV:Envelope  xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope"  xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:xsd="http://www.w3.org/2001/XMLSchema"  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"  xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery"  xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex"  xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"   xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"  xmlns:wsa5="http://www.w3.org/2005/08/addressing"  xmlns:xmime="http://tempuri.org/xmime.xsd"  xmlns:xop="http://www.w3.org/2004/08/xop/include"  xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2"  xmlns:wstop="http://docs.oasis-open.org/wsn/t-1"  xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2"  xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2"  xmlns:tt="http://www.onvif.org/ver10/schema"  xmlns:ter="http://www.onvif.org/ver10/error"  xmlns:tns1="http://www.onvif.org/ver10/topics"  xmlns:tds="http://www.onvif.org/ver10/device/wsdl"  xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl"  xmlns:trt="http://www.onvif.org/ver10/media/wsdl"  xmlns:tev="http://www.onvif.org/ver10/events/wsdl"  xmlns:tdn="http://www.onvif.org/ver10/network/wsdl"  xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl"  xmlns:trp="http://www.onvif.org/ver10/replay/wsdl"  xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl"  xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl"  xmlns:tr2="http://www.onvif.org/ver20/media/wsdl"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Sender</SOAP-ENV:Value><SOAP-ENV:Subcode><SOAP-ENV:Value>ter:InvalidArgVal</SOAP-ENV:Value></SOAP-ENV:Subcode></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text   xml:lang="en">error</SOAP-ENV:Text></SOAP-ENV:Reason></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
onvif.1 | 2023-09-05 14:31:22.913 | info | Found devices:
onvif.1 | 2023-09-05 14:31:22.913 | info | Manual search finished
onvif.1 | 2023-09-05 14:31:22.912 | info | Data: undefined xml: undefined
onvif.1 | 2023-09-05 14:31:22.912 | debug | Error:  ONVIF SOAP Fault: error    at  /opt/iobroker/node_modules/iobroker.onvif/lib/onvif/lib/utils.js:113:19     at Parser.<anonymous>  (/opt/iobroker/node_modules/xml2js/lib/parser.js:304:18)    at  Parser.emit (events.js:400:28)    at Parser.emit (domain.js:475:12)     at SAXParser.onclosetag  (/opt/iobroker/node_modules/xml2js/lib/parser.js:262:26)    at emit  (/opt/iobroker/node_modules/sax/lib/sax.js:624:35)    at emitNode  (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)    at closeTag  (/opt/iobroker/node_modules/sax/lib/sax.js:889:7)    at SAXParser.write  (/opt/iobroker/node_modules/sax/lib/sax.js:1436:13)    at  Parser.exports.Parser.Parser.parseString  (/opt/iobroker/node_modules/xml2js/lib/parser.js:323:31)
onvif.1 | 2023-09-05 14:31:22.910 | info | Error Error: ONVIF SOAP Fault: error
onvif.1 | 2023-09-05 14:31:22.909 | error | Failed to login to 10.100.3.6:2020 with admin:y***************-
onvif.1 | 2023-09-05 14:31:22.906 | debug | Raw  response: <?xml version="1.0"  encoding="UTF-8"?><SOAP-ENV:Envelope  xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope"  xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:xsd="http://www.w3.org/2001/XMLSchema"  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"  xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery"  xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex"  xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"   xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"  xmlns:wsa5="http://www.w3.org/2005/08/addressing"  xmlns:xmime="http://tempuri.org/xmime.xsd"  xmlns:xop="http://www.w3.org/2004/08/xop/include"  xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2"  xmlns:wstop="http://docs.oasis-open.org/wsn/t-1"  xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2"  xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2"  xmlns:tt="http://www.onvif.org/ver10/schema"  xmlns:ter="http://www.onvif.org/ver10/error"  xmlns:tns1="http://www.onvif.org/ver10/topics"  xmlns:tds="http://www.onvif.org/ver10/device/wsdl"  xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl"  xmlns:trt="http://www.onvif.org/ver10/media/wsdl"  xmlns:tev="http://www.onvif.org/ver10/events/wsdl"  xmlns:tdn="http://www.onvif.org/ver10/network/wsdl"  xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl"  xmlns:trp="http://www.onvif.org/ver10/replay/wsdl"  xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl"  xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl"  xmlns:tr2="http://www.onvif.org/ver20/media/wsdl"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Sender</SOAP-ENV:Value><SOAP-ENV:Subcode><SOAP-ENV:Value>ter:InvalidArgVal</SOAP-ENV:Value></SOAP-ENV:Subcode></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text   xml:lang="en">error</SOAP-ENV:Text></SOAP-ENV:Reason></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
onvif.1 | 2023-09-05 14:31:22.770 | debug | Raw  response: <?xml version="1.0"  encoding="UTF-8"?><SOAP-ENV:Envelope  xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope"  xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:xsd="http://www.w3.org/2001/XMLSchema"  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"  xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery"  xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex"  xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"   xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"  xmlns:wsa5="http://www.w3.org/2005/08/addressing"  xmlns:xmime="http://tempuri.org/xmime.xsd"  xmlns:xop="http://www.w3.org/2004/08/xop/include"  xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2"  xmlns:wstop="http://docs.oasis-open.org/wsn/t-1"  xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2"  xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2"  xmlns:tt="http://www.onvif.org/ver10/schema"  xmlns:ter="http://www.onvif.org/ver10/error"  xmlns:tns1="http://www.onvif.org/ver10/topics"  xmlns:tds="http://www.onvif.org/ver10/device/wsdl"  xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl"  xmlns:trt="http://www.onvif.org/ver10/media/wsdl"  xmlns:tev="http://www.onvif.org/ver10/events/wsdl"  xmlns:tdn="http://www.onvif.org/ver10/network/wsdl"  xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl"  xmlns:trp="http://www.onvif.org/ver10/replay/wsdl"  xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl"  xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl"  xmlns:tr2="http://www.onvif.org/ver20/media/wsdl"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><tr2:GetProfilesResponse><tr2:Profiles  fixed="true"  token="profile_1"><tr2:Name>mainStream</tr2:Name><tr2:Configurations><tr2:VideoSource   token="vsconf"><tt:Name>VideoSourceConfig</tt:Name><tt:UseCount>3</tt:UseCount><tt:SourceToken>raw_vs1</tt:SourceToken><tt:Bounds  height="720" width="1280" y="0"  x="0"></tt:Bounds></tr2:VideoSource><tr2:AudioSource  token="asconf"><tt:Name>AudioSourceConfig</tt:Name><tt:UseCount>3</tt:UseCount><tt:SourceToken>raw_as1</tt:SourceToken></tr2:AudioSource><tr2:VideoEncoder  token="main"  GovLength="25"><tt:Name>VideoEncoder_1</tt:Name><tt:UseCount>1</tt:UseCount><tt:Encoding>H265</tt:Encoding><tt:Resolution><tt:Width>2304</tt:Width><tt:Height>1296</tt:Height></tt:Resolution><tt:RateControl   ConstantBitRate="false"><tt:FrameRateLimit>25</tt:FrameRateLimit><tt:BitrateLimit>3584</tt:BitrateLimit></tt:RateControl><tt:Multicast><tt:Address><tt:Type>IPv4</tt:Type><tt:IPv4Address>0.0.0.0</tt:IPv4Address></tt:Address><tt:Port>0</tt:Port><tt:TTL>0</tt:TTL><tt:AutoStart>false</tt:AutoStart></tt:Multicast><tt:Quality>5</tt:Quality></tr2:VideoEncoder><tr2:AudioEncoder   token="raw_as1"><tt:Name>AudioSourceConfig</tt:Name><tt:UseCount>3</tt:UseCount><tt:Encoding>G711</tt:Encoding><tt:Multicast><tt:Address><tt:Type>IPv4</tt:Type><tt:IPv4Address>0.0.0.0</tt:IPv4Address></tt:Address><tt:Port>0</tt:Port><tt:TTL>0</tt:TTL><tt:AutoStart>false</tt:AutoStart></tt:Multicast><tt:Bitrate>65536</tt:Bitrate><tt:SampleRate>11000</tt:SampleRate></tr2:AudioEncoder><tr2:Analytics   token="VideoAnalyticsToken"><tt:Name>VideoAnalyticsName</tt:Name><tt:UseCount>2</tt:UseCount><tt:AnalyticsEngineConfiguration><tt:AnalyticsModule  Name="MyCellMotionModule"  Type="tt:CellMotionEngine"><tt:Parameters><tt:SimpleItem  Value="50" Name="Sensitivity"></tt:SimpleItem><tt:SimpleItem  Value="on" Name="Enabled"></tt:SimpleItem><tt:ElementItem  Name="Layout"><tt:CellLayout Rows="18"  Columns="22"><tt:Transformation><tt:Translate y="-1"  x="-1"></tt:Translate><tt:Scale y="0.109999999"  x="0.0900000036"></tt:Scale></tt:Transformation></tt:CellLayout></tt:ElementItem></tt:Parameters></tt:AnalyticsModule><tt:AnalyticsModule  Name="MyTamperDetecModule"  Type="tt:TamperEngine"><tt:Parameters><tt:SimpleItem  Value="50" Name="Sensitivity"></tt:SimpleItem><tt:SimpleItem  Value="off"  Name="Enabled"></tt:SimpleItem></tt:Parameters></tt:AnalyticsModule></tt:AnalyticsEngineConfiguration><tt:RuleEngineConfiguration><tt:Rule  Name="MyMotionDetectorRule"  Type="tt:CellMotionDetector"><tt:Parameters><tt:SimpleItem  Value="0P8A8A=="  Name="ActiveCells"></tt:SimpleItem><tt:SimpleItem Value="5"  Name="MinCount"></tt:SimpleItem><tt:SimpleItem Value="1000"  Name="AlarmOnDelay"></tt:SimpleItem><tt:SimpleItem  Value="1000"  Name="AlarmOffDelay"></tt:SimpleItem></tt:Parameters></tt:Rule><tt:Rule  Name="MyTamperDetectorRule"  Type="tt:TamperDetector"><tt:Parameters></tt:Parameters></tt:Rule></tt:RuleEngineConfiguration></tr2:Analytics><tr2:PTZ   token="PTZTOKEN"><tt:Name>PTZ</tt:Name><tt:UseCount>2</tt:UseCount><tt:NodeToken>PTZNODETOKEN</tt:NodeToken><tt:DefaultAbsolutePantTiltPositionSpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:DefaultAbsolutePantTiltPositionSpace><tt:DefaultRelativePanTiltTranslationSpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace</tt:DefaultRelativePanTiltTranslationSpace><tt:DefaultContinuousPanTiltVelocitySpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace</tt:DefaultContinuousPanTiltVelocitySpace><tt:DefaultPTZSpeed><tt:PanTilt  space="http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace"  x="1.000000" y  ="0.890000"></tt:PanTilt></tt:DefaultPTZSpeed><tt:DefaultPTZTimeout>PT180S</tt:DefaultPTZTimeout><tt:PanTiltLimits><tt:Range><tt:URI>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:URI><tt:XRange><tt:Min>-1</tt:Min><tt:Max>1</tt:Max></tt:XRange><tt:YRange><tt:Min>-1</tt:Min><tt:Max>1</tt:Max></tt:YRange></tt:Range></tt:PanTiltLimits><tt:Extension><tt:PTControlDirection><tt:EFlip><tt:Mode>OFF</tt:Mode></tt:EFlip><tt:Reverse><tt:Mode>OFF</tt:Mode></tt:Reverse></tt:PTControlDirection></tt:Extension></tr2:PTZ></tr2:Configurations></tr2:Profiles><tr2:Profiles  fixed="true"  token="profile_2"><tr2:Name>minorStream</tr2:Name><tr2:Configurations><tr2:VideoSource   token="vsconf"><tt:Name>VideoSourceConfig</tt:Name><tt:UseCount>3</tt:UseCount><tt:SourceToken>raw_vs1</tt:SourceToken><tt:Bounds  height="720" width="1280" y="0"  x="0"></tt:Bounds></tr2:VideoSource><tr2:AudioSource  token="asconf"><tt:Name>AudioSourceConfig</tt:Name><tt:UseCount>3</tt:UseCount><tt:SourceToken>raw_as1</tt:SourceToken></tr2:AudioSource><tr2:VideoEncoder  token="minor"  GovLength="25"><tt:Name>VideoEncoder_2</tt:Name><tt:UseCount>1</tt:UseCount><tt:Encoding>H265</tt:Encoding><tt:Resolution><tt:Width>640</tt:Width><tt:Height>480</tt:Height></tt:Resolution><tt:RateControl   ConstantBitRate="false"><tt:FrameRateLimit>25</tt:FrameRateLimit><tt:BitrateLimit>512</tt:BitrateLimit></tt:RateControl><tt:Multicast><tt:Address><tt:Type>IPv4</tt:Type><tt:IPv4Address>0.0.0.0</tt:IPv4Address></tt:Address><tt:Port>0</tt:Port><tt:TTL>0</tt:TTL><tt:AutoStart>false</tt:AutoStart></tt:Multicast><tt:Quality>5</tt:Quality></tr2:VideoEncoder><tr2:AudioEncoder   token="raw_as1"><tt:Name>AudioSourceConfig</tt:Name><tt:UseCount>3</tt:UseCount><tt:Encoding>G711</tt:Encoding><tt:Multicast><tt:Address><tt:Type>IPv4</tt:Type><tt:IPv4Address>0.0.0.0</tt:IPv4Address></tt:Address><tt:Port>0</tt:Port><tt:TTL>0</tt:TTL><tt:AutoStart>false</tt:AutoStart></tt:Multicast><tt:Bitrate>65536</tt:Bitrate><tt:SampleRate>11000</tt:SampleRate></tr2:AudioEncoder><tr2:Analytics   token="VideoAnalyticsToken"><tt:Name>VideoAnalyticsName</tt:Name><tt:UseCount>2</tt:UseCount><tt:AnalyticsEngineConfiguration><tt:AnalyticsModule  Name="MyCellMotionModule"  Type="tt:CellMotionEngine"><tt:Parameters><tt:SimpleItem  Value="50" Name="Sensitivity"></tt:SimpleItem><tt:SimpleItem  Value="on" Name="Enabled"></tt:SimpleItem><tt:ElementItem  Name="Layout"><tt:CellLayout Rows="18"  Columns="22"><tt:Transformation><tt:Translate y="-1"  x="-1"></tt:Translate><tt:Scale y="0.109999999"  x="0.0900000036"></tt:Scale></tt:Transformation></tt:CellLayout></tt:ElementItem></tt:Parameters></tt:AnalyticsModule><tt:AnalyticsModule  Name="MyTamperDetecModule"  Type="tt:TamperEngine"><tt:Parameters><tt:SimpleItem  Value="50" Name="Sensitivity"></tt:SimpleItem><tt:SimpleItem  Value="off"  Name="Enabled"></tt:SimpleItem></tt:Parameters></tt:AnalyticsModule></tt:AnalyticsEngineConfiguration><tt:RuleEngineConfiguration><tt:Rule  Name="MyMotionDetectorRule"  Type="tt:CellMotionDetector"><tt:Parameters><tt:SimpleItem  Value="0P8A8A=="  Name="ActiveCells"></tt:SimpleItem><tt:SimpleItem Value="5"  Name="MinCount"></tt:SimpleItem><tt:SimpleItem Value="1000"  Name="AlarmOnDelay"></tt:SimpleItem><tt:SimpleItem  Value="1000"  Name="AlarmOffDelay"></tt:SimpleItem></tt:Parameters></tt:Rule><tt:Rule  Name="MyTamperDetectorRule"  Type="tt:TamperDetector"><tt:Parameters></tt:Parameters></tt:Rule></tt:RuleEngineConfiguration></tr2:Analytics><tr2:PTZ   token="PTZTOKEN"><tt:Name>PTZ</tt:Name><tt:UseCount>2</tt:UseCount><tt:NodeToken>PTZNODETOKEN</tt:NodeToken><tt:DefaultAbsolutePantTiltPositionSpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:DefaultAbsolutePantTiltPositionSpace><tt:DefaultRelativePanTiltTranslationSpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace</tt:DefaultRelativePanTiltTranslationSpace><tt:DefaultContinuousPanTiltVelocitySpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace</tt:DefaultContinuousPanTiltVelocitySpace><tt:DefaultPTZSpeed><tt:PanTilt  space="http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace"  x="1.000000" y  ="0.890000"></tt:PanTilt></tt:DefaultPTZSpeed><tt:DefaultPTZTimeout>PT180S</tt:DefaultPTZTimeout><tt:PanTiltLimits><tt:Range><tt:URI>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:URI><tt:XRange><tt:Min>-1</tt:Min><tt:Max>1</tt:Max></tt:XRange><tt:YRange><tt:Min>-1</tt:Min><tt:Max>1</tt:Max></tt:YRange></tt:Range></tt:PanTiltLimits><tt:Extension><tt:PTControlDirection><tt:EFlip><tt:Mode>OFF</tt:Mode></tt:EFlip><tt:Reverse><tt:Mode>OFF</tt:Mode></tt:Reverse></tt:PTControlDirection></tt:Extension></tr2:PTZ></tr2:Configurations></tr2:Profiles><tr2:Profiles  fixed="true"  token="profile_3"><tr2:Name>jpegStream</tr2:Name><tr2:Configurations><tr2:VideoSource   token="vsconf"><tt:Name>VideoSourceConfig</tt:Name><tt:UseCount>3</tt:UseCount><tt:SourceToken>raw_vs1</tt:SourceToken><tt:Bounds  height="720" width="1280" y="0"  x="0"></tt:Bounds></tr2:VideoSource><tr2:AudioSource  token="asconf"><tt:Name>AudioSourceConfig</tt:Name><tt:UseCount>3</tt:UseCount><tt:SourceToken>raw_as1</tt:SourceToken></tr2:AudioSource><tr2:VideoEncoder  token="jpeg"  GovLength="25"><tt:Name>VideoEncoder_3</tt:Name><tt:UseCount>1</tt:UseCount><tt:Encoding>JPEG</tt:Encoding><tt:Resolution><tt:Width>640</tt:Width><tt:Height>360</tt:Height></tt:Resolution><tt:RateControl   ConstantBitRate="true"><tt:FrameRateLimit>1</tt:FrameRateLimit><tt:BitrateLimit>512</tt:BitrateLimit></tt:RateControl><tt:Multicast><tt:Address><tt:Type>IPv4</tt:Type><tt:IPv4Address>0.0.0.0</tt:IPv4Address></tt:Address><tt:Port>0</tt:Port><tt:TTL>0</tt:TTL><tt:AutoStart>false</tt:AutoStart></tt:Multicast><tt:Quality>1</tt:Quality></tr2:VideoEncoder><tr2:AudioEncoder   token="raw_as1"><tt:Name>AudioSourceConfig</tt:Name><tt:UseCount>3</tt:UseCount><tt:Encoding>G711</tt:Encoding><tt:Multicast><tt:Address><tt:Type>IPv4</tt:Type><tt:IPv4Address>0.0.0.0</tt:IPv4Address></tt:Address><tt:Port>0</tt:Port><tt:TTL>0</tt:TTL><tt:AutoStart>false</tt:AutoStart></tt:Multicast><tt:Bitrate>65536</tt:Bitrate><tt:SampleRate>11000</tt:SampleRate></tr2:AudioEncoder><tr2:Analytics   token="VideoAnalyticsToken"><tt:Name>VideoAnalyticsName</tt:Name><tt:UseCount>2</tt:UseCount><tt:AnalyticsEngineConfiguration><tt:AnalyticsModule  Name="MyCellMotionModule"  Type="tt:CellMotionEngine"><tt:Parameters><tt:SimpleItem  Value="50" Name="Sensitivity"></tt:SimpleItem><tt:SimpleItem  Value="on" Name="Enabled"></tt:SimpleItem><tt:ElementItem  Name="Layout"><tt:CellLayout Rows="18"  Columns="22"><tt:Transformation><tt:Translate y="-1"  x="-1"></tt:Translate><tt:Scale y="0.109999999"  x="0.0900000036"></tt:Scale></tt:Transformation></tt:CellLayout></tt:ElementItem></tt:Parameters></tt:AnalyticsModule><tt:AnalyticsModule  Name="MyTamperDetecModule"  Type="tt:TamperEngine"><tt:Parameters><tt:SimpleItem  Value="50" Name="Sensitivity"></tt:SimpleItem><tt:SimpleItem  Value="off"  Name="Enabled"></tt:SimpleItem></tt:Parameters></tt:AnalyticsModule></tt:AnalyticsEngineConfiguration><tt:RuleEngineConfiguration><tt:Rule  Name="MyMotionDetectorRule"  Type="tt:CellMotionDetector"><tt:Parameters><tt:SimpleItem  Value="0P8A8A=="  Name="ActiveCells"></tt:SimpleItem><tt:SimpleItem Value="5"  Name="MinCount"></tt:SimpleItem><tt:SimpleItem Value="1000"  Name="AlarmOnDelay"></tt:SimpleItem><tt:SimpleItem  Value="1000"  Name="AlarmOffDelay"></tt:SimpleItem></tt:Parameters></tt:Rule><tt:Rule  Name="MyTamperDetectorRule"  Type="tt:TamperDetector"><tt:Parameters></tt:Parameters></tt:Rule></tt:RuleEngineConfiguration></tr2:Analytics><tr2:PTZ   token="PTZTOKEN"><tt:Name>PTZ</tt:Name><tt:UseCount>2</tt:UseCount><tt:NodeToken>PTZNODETOKEN</tt:NodeToken><tt:DefaultAbsolutePantTiltPositionSpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:DefaultAbsolutePantTiltPositionSpace><tt:DefaultRelativePanTiltTranslationSpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace</tt:DefaultRelativePanTiltTranslationSpace><tt:DefaultContinuousPanTiltVelocitySpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace</tt:DefaultContinuousPanTiltVelocitySpace><tt:DefaultPTZSpeed><tt:PanTilt  space="http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace"  x="1.000000" y  ="0.890000"></tt:PanTilt></tt:DefaultPTZSpeed><tt:DefaultPTZTimeout>PT180S</tt:DefaultPTZTimeout><tt:PanTiltLimits><tt:Range><tt:URI>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:URI><tt:XRange><tt:Min>-1</tt:Min><tt:Max>1</tt:Max></tt:XRange><tt:YRange><tt:Min>-1</tt:Min><tt:Max>1</tt:Max></tt:YRange></tt:Range></tt:PanTiltLimits><tt:Extension><tt:PTControlDirection><tt:EFlip><tt:Mode>OFF</tt:Mode></tt:EFlip><tt:Reverse><tt:Mode>OFF</tt:Mode></tt:Reverse></tt:PTControlDirection></tt:Extension></tr2:PTZ></tr2:Configurations></tr2:Profiles></tr2:GetProfilesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
onvif.1 | 2023-09-05 14:31:22.457 | debug | Raw  request: <s:Envelope  xmlns:s="http://www.w3.org/2003/05/soap-envelope"  xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header><Security  s:mustUnderstand="1"  xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Username>admin</Username><Password   Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">H4Q2xoZ7d3YsS/ivTWfC2SbTf3c=</Password><Nonce   EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">SdGzLEfWeKml/OXXFoUX9A==</Nonce><Created   xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-09-05T11:31:21.687Z</Created></UsernameToken></Security></s:Header><s:Body  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetVideoSources  xmlns="http://www.onvif.org/ver10/media/wsdl"/></s:Body></s:Envelope>
onvif.1 | 2023-09-05 14:31:22.445 | debug | Raw  request: <s:Envelope  xmlns:s="http://www.w3.org/2003/05/soap-envelope"  xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header><Security  s:mustUnderstand="1"  xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Username>admin</Username><Password   Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">r87xyYfrYbTxEUJuVZLzQCB84MA=</Password><Nonce   EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">+3qso/qZPq1gJQShvDXk0Q==</Nonce><Created   xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-09-05T11:31:21.659Z</Created></UsernameToken></Security></s:Header><s:Body  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetProfiles  xmlns="http://www.onvif.org/ver20/media/wsdl"><Type>All</Type></GetProfiles></s:Body></s:Envelope>

</body>
</html>
`

**Comment by TA2k** [comment]
Das xml scheint fehlerhaft zu sein.. gibt es denn vielleicht ein firmware update oder so
